version: "3.9"

services:
  db:
    container_name: ratevolut-db
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ratevolut
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ratevolut"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    container_name: ratevolut-app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SPRING_PROFILES_ACTIVE=dev
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/ratevolut
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      APP_FRANKFURTER_BASE_URL: https://api.frankfurter.dev/v2
    depends_on:
      db:
        condition: service_healthy