spring.application.name=RATEVOLUT
spring.profiles.active=dev
spring.datasource.url=jdbc:postgresql://localhost:5432/ratevolut
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml